<div class="UserToolbar">
<?php if (isset($this->loginForm)) :?>
    <?php echo $this->loginForm;?>
</div>
<a href="/register" style="display:block;float:right;font-size:0.70em;margin-top:-10px;">Register Here</a>
<?php else :?>
    <input type="button" style="float:right;" value="Logout" onclick="layout_usertoolbar.logout();">
    <div style="width:270px;padding-top:3px;">
        Welcome! You are logged in as: <b><?php echo $this->user->email;?></b>
    </div>
</div>
<?php endif;?>
