<div class="loginContainer">
    <h1>St. John Admin</h1>
    <div class="error">
    <?php if (isset($this->error)) :?>
        <?php echo $this->error;?>
    <?php endif;?>
    </div>
    <form action"/" method="post">
        <label for="email">Email</label>
        <br/>
        <input id="email" name="email" type="text" autofocus="autofocus"/>
        <br/>
        <label for="password">Password</label>
        <br/>
        <input id="password" name="password" type="password" />
        <br/>
        <input type="submit" value="Log In"/>
    </form>
</div>
