<div id="adminView">
  <form>
  <select id="veiwToUpdate" onchange="getFile()">
	<option value="nothing" selected="selected">Select a Menu Item</option>
	<option value="http://localhost">Home1</option>
  <?php foreach($this->menuItems as $key=>$value) : ?>
	<option value=<?php echo $key;?>><?php echo $value;?></option>
  <?php endforeach?>	
     </select>
  </form>
 

 
  <div id="previewContent">
	<iframe src="about:blank" id="preview-iframe" frameborder='0' allowTransparency="true" scrolling="no">
           <p>Your browser does not support iframes.</p>
        </iframe>
  </div><!--end the preview div -->
  <div id="newContent">
	<form>
		<textarea cols="125" rows="15" id="editContent" onkeyup="display()" ></textarea>
	</form>
  </div><!-- end the admin text box div -->

</div><!-- end the adminView div -->
