<div class="indexContent">
    <h1>Welcome To The St John Admin Page!</h1>
    Some things to remember:
    <ul>
        <li>Everything you do here affects the site!</li>
        <li>Do not leave your computer unattended while logged in</li>
        <li>Never give out your password</li>
        <li>Be careful who you grant access to. Changes made are irreversable.</li>
    </ul>
    <br/>
    <br/>
    If you have any questions, concerns, or things just break. Feel free to email the developer at <a href="mailto:matthew_kosolofski@hotmail.com">matthew_kosolofski@hotmail.com</a>
</div>
