<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Admin Page</title>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
    </head>
    <body>
        <?php if (!isset($this->hideNav)):
            echo $this->partial('/layout/_navigation.phtml');
        endif;?>
        <div class="content">
            <?php echo $this->layout()->content;?>
        </div>
    </body>
</html>
