<h1>St John Luthern Church</h1>
<div class="map">
        <a href="http://www.google.ca/local?hl=en&lr=&q=St+John+Lutheran&near=Calgary,+AB&latlng=51039877,-114080796,5519230273787071585" ><img src="/images/dynamic/directions2.jpg"/></a>
</div>
<br/>
<div class="details">
    <section>
        <h2>Address</h2>
        <p>
            204 6a Street NE<br/>
            Calgary, AB T2E_4A5<br/>
            <br/>
            <em>Find us @ Corner of 1st Avenue and 6A St</em>
        </p>
    </section>
    <section>
        <h2>Phone</h2>
        <p>
            (403) 262-2862
        </p>
    </section>
    <section>
        <h2>Email</h2>
        <p>
            Email us @: stjohnlc@telus.net
        </p>
    </section>
    <section>
        <h2>Staff</h2>
        <p>
            Pastor: The Rev. Arnold Alksne<br/>
            Organist and Choir Director: Alma Sloboda<br/>
            Chairperson: Yvette Straub<br/>
            Secretary: Earl Olson<br/>
            Financial Secretary/Administrative Assistant: Dorothy Schumaker<br/>
        </p>
    </section>
    <section>
        <h2>Hours of Operation</h2>
        <p>Monday-Friday: 9am to 5pm</p>
    </section>
</div>
