<br/><br/>
<div>
<center><h1>St John Luthern Church</h1>

    <div>
        <em>Find us @ Corner of 1st Avenue and 6A St</em><br/><br/>
        204 6a Street NE<br/>
        Calgary, AB T2E_4A5<br/>
        (403) 262-2862<br/> 
    </div>
    <br/> 
    <br/>

    Email us at: stjohnlc@telus.net 

    Pastor: The Rev. Arnold Alksne 
    Organist and Choir Director: Alma Sloboda 
    Chairperson: Yvette Straub 
    Secretary: Earl Olson 
    Financial Secretary/Administrative Assistant: Dorothy Schumaker
    </center>
</div>
