<div class="staticContent">
    <h1>HISTORY</h1>  
    St. John was founded in 1909 by German refugees escaping persecution in Russia. Since then there have been many changes. Instead of being on the very edge of the city, we are now in the core. The ethnic diversity in the community has changed several times and continues to do so. Some things have not changed, we still have refugees living among us and there is still a need to emphasize family, forgiveness and caring for others.
</div>
