<h1>
    <img src="/images/about-us/history/history.png" alt="History"/>
</h1>  
<!-- St. John was founded in 1909 by German refugees escaping persecution in Russia. Since then there have been many changes. Instead of being on the very edge of the city, we are now in the core. The ethnic diversity in the community has changed several times and continues to do so. Some things have not changed, we still have refugees living among us and there is still a need to emphasize family, forgiveness and caring for others. -->

<!-- taken from http://churchesinbridgeland.wordpress.com/2012/03/27/st-john-lutheran-church/ -->
<section>
    <h2>Church History</h2>
    <div id="slides">
        <div class="slides_container">
            <div>
                <img src="/images/about-us/history/st_john_1909.png" alt="st john 1909">
            </div>
        </div>
    </div>
    <p style="margin: 0;">
        In the mid to late 1800′s, the Canadian government was in need of people to settle the west. The Americans were too close for the Canadians to allow the land to go  “un-claimed” for much longer. Canada began massive campaigning in the farming communities of Europe. By the 1980′s many Germans, mostly from Eastern European countries like Russia, began to settle in Alberta. Between 1986 and 1914 a large number of settlers came to Canada. In Alberta, many settled in the Bridgeland/Riverside area giving it the name “German Town.” Members of the Blackfoot tribe watched as this area grew up on the land and by 1910, became a part of Calgary (also see file on the City of Calgary page).<br/><br/>

        By 1909 one of the German-Russian groups living in Bridgeland began to meet for both the purpose of holding service and for discussing the possibility of a creating a Church. They contacted their former minister in Russia, Felix Coulin (Kulin) and he advised them to join the Iowa or Ohio Lutheran Synod. This they did and in July 1909, Rev. Paul Bung was sent form Iowa Synod to help them establish a church. The name “Die Evengelelische Lutherische Sankt Johannes Gemeinde Zu Calgary” or “The Evangelical Lutheran Church, St. John’s Congregation in Calgary ” was chosen on July 22, 1909. The congregation met in homes or in the Baptist hall on 1st Ave and 8th Street before construction of a church on their current property began in November 1909.<br/><br/>

        In october of 1909 the first minister, Rev. Karl Boetke, was inaugurated and a German School was established in the home of Johannes Schneidmueller for children to attend Tuesday and Friday evenings for German lessons and religious teachings. The congregation continued to meet in various location until the building was dedicated on July 10, 1910.<br/><br/>

        When Rev. Boetke left in July of 1913, it took the congregation a few years to find a permanent minister again and between November 1914 and December 1915 minister P.W.H Loescke of the Zion Church lead both the Zion Church and St. John’s. Due to this trouble, the congregation asked to be allowed to join the Ohio Synod they were granted their request.  In 1916 Rev. George Stamm came on as minister and stayed until September 1918.During Rev. Stamm’s time as minister, the Zion Church disbanded and the members were invited to join St. John’s congregation. Also durring Re. Stamm’s ministry, there was a lot of tension in the city around those of German heritage. The Riverside Hotel, just north of Langevin Bridge, was marched on by a mob and the interior vandalized and destroyed because the mobbers thought the hotel was still owned by Germans. Also, a regulation was made that banned all Germans from holding meetings in their German language.<br/><br/>

        A number of ministers came and went over the years but the church congregation remained strong. In 1923 the City of Calgary prohibited St. Johns from continuing tho have their German school on the premises of the Church. They had to rent a separate building. This caused some issues as money had to be redirected towards renting another building and some parents refused to cooperate leaving the minister without his promised pay.<br/><br/>

        But still the congregation held together and in 1937 they decided it was time for a basement to be added. They raised the church and the men hand dug one out. They finished the job without help from any contractors.<br/><br/>

        Eventually the congregation outgrew its current building and in 1945 talks began on what to do about this problem. The purchase of the Moravian building, the place where St. Matthew’s now calls home, was discussed and decided against. A red isle runner was added and stained glass window was donated in 1946 & 1947 respectively. But it wouldn’t be long before talks of renovations and possible moves would come up again.<br/><br/>

        In 1954, plans for a parsonage and education units was realized and construction began in June 1954 and was completed in 1955. On May 2, 1955 the congregation adopted the name St. John Lutheran Church, after much discussion. A number of other renovations happened such as new tiles in auditorium and new shingles on the roof as well as the purchase of an electric organ. Some renovations had to be done to accommodate this new organ.<br/><br/>

        The 1960′s saw talks of relocation again but nothing could be agreed upon. Finally, the church was given the opportunity to purchase the lot next to them. This allowed for expansion right at their current location. The building of a newer more modern church began thanks to individual loans from parishioners to the church.<br/><br/>

        The ground breaking ceremony was held August 17, 1968. The new church was constructed on the North side of the old church and once that was complete, the old church was torn down and the educational unit and offices were built. Dedication of the new building happened on June 8 1969.<br/><br/>

        Many anniversaries, events, gatherings and charitable projects have been put together by the parish over the years. In 2009 they celebrated their 100th anniversary. I could not find a newspaper article describing the event but I did find a write-up about it from Bill Benner in the “American Historical Society of Germans from Russia Calgary Chapter.” The celebration was held over 2 days in July with “the opening of a time capsule, an open house where church pictures and records were on display and a banquet at the Coast Plaza hotel.” A letter from Buckingham Palace was there with congratulations from the Queen. A copy of this letter can be found at the front of the history book.<br/><br/>
    </p>
</section>
<section>
    <h2>Pastor History</h2>
    <p>The following pastors have served the congregation of St. John Lutheran Church:</p>
    <ul>
        <li>Karl Boetke (1909-1913)</li>
        <li>Henry James Reinecke (1913-1914)</li>
        <li>Peter W.H. Loeschke (1914-1915)</li>
        <li>George Stamm (1916-1918)</li>
        <li>Henry Obermowe (1918-1919)</li>
        <li>Albert Schormann (1919-1923)</li>
        <li>Emil Schiewe (1923-1924)</li>
        <li>Karl Pohlmann (1924-1931)</li>
        <li>Karl Holfeld (1931-1940)</li>
        <li>Peter H. Mohr (1940)</li>
        <li>Walter Rossback (1941-1942)</li>
        <li>Rudolf Huget (1943-1945)</li>
        <li>John Leinweber (1945-1953)</li>
        <li>Edward Krempin (1953-1954)</li>
        <li>Carl J. Daeschel (1954-1963)</li>
        <li>Hans M. Steinert (1963-1982)</li>
        <li>James Buenting (1982-1994)</li>
        <li>K. Henry Reintze (1994-1995)</li>
        <li>Markus Wilhelm (1995-2003)</li>
        <li>Earl Schartner (2003-2004)</li>
        <li>Arnold Alksne (2004-)</li>
    </ul>
</section>
