<h1>
    <img src="/images/about-us/pastors_page/pastors_page.png" alt="Pastor's Page" width="201px" height="56px"/>
</h1>
<div class="pictureFloatLeft">
    <?php echo $this->partial('layout/_picture.phtml', array('source' => '/images/about-us/pastors_page/pastor_arnie.jpg', 'alt' => 'Pastor Arnie'));?>
</div>
<p style="margin-top:0">
    Greetings in the name of our Lord Jesus Christ, who was, who is, and who is coming again as He promised at His ascension into glory.
    <br/>
    <br/>
    As the pastor of St. John Lutheran Church, Calgary, AB, I warmly welcome you, both to our website as well as to our congregation. We are a Christian Church who worship and celebrate God's goodness through the teachings and practices of the Evangelical Lutheran Church in Canada. We believe in the Triune God, Father, Son, and Holy Spirit (not three gods, but one God coeternal and coequal yet three distinct persons).
    <br/>
    <br/>
    Jesus Christ, God's son, is our human connection with God, God who came to His creation to experience the human life with its joys, temptations, pain and sorrows. Jesus Christ having experienced our humanity Himself was sent by the Father, and willingly gave His life as a ransom for our salvation. We believe that Jesus paid the price and has freed us from our sins, from death, and from the power of evil. So out of thanksgiving to God for what He has done for us, through His Son, we go into the world to share that love of God in service to our neighbors.
    <br/>
    <br/>
    We welcome you to come and worship with us in the hope that all may experience the love God has for His creation.
    <br/>
    <br/>
    -- Pastor Arnie
</p>
