<div class="eventDate">Sep 12, 2012 - 2:00pm</div>
Model train meeting. Fun for all ages!
<div class="eventDivider"></div>
<div class="eventDate">Oct 28, 2012 - 8:00am</div>
Trip to Las Vegas to see Matt and Anna.
<div class="eventDivider"></div>
<div class="eventDate">Dec 14, 2012 - 12:00pm</div>
Potluck after service. All guests welcome!
<div class="eventDivider"></div>
<div class="eventDate">Feb 01, 2013 - 9:45am</div>
Snow shovelling contest. Who can shovel the fastest!
<div class="eventDivider"></div>
<div class="eventDate">Apr 28, 2013 - 2:00pm</div>
Hamburger eating contest.
