<div>
    <div>
        <div class="columnA">
            <div>
                <div class="worshipTime"> 
                    <img src="/images/index/index/worship_time.png"/>
                    <div style="text-align:center;">
                        <?echo $this->partial('index/_worshiptime.phtml');?>
                    </div>
                </div>
            </div>
            <div>
                <div class="events"> 
                    <img src="/images/index/index/events.png"/>
                    <div>
                        <div style="height:200px;overflow-y:scroll;">
                            <?echo $this->partial('index/_events.phtml');?>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="keepInTouch"> 
                    <img src="/images/index/index/keep_in_touch.png"/>
                    <div style="text-align:center">
                        Join our mailing list to keep informed of our latest announcements!
                        <form action="http://stjohncalgary.us1.list-manage1.com/subscribe/post?u=d1ac68a47e4f603ad62c2fcf8&amp;id=3b34af7599" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank">
                            <label style="font-weight:bold">Email:</label>
                            <input type="text" name="EMAIL" id="mce-EMAIL" style="width:120px">
                            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn">
                        </form>
                    </div>
                </div>
            </div>
            <div>
                <div class="contact"> 
                    <img src="/images/index/index/contact.png"/>
                    <div>
                        <div style="text-align:center">
                            <b>St. John Lutheran Church</b>
                            <br/>
                            204 6a Street NE
                            <br/>
                            Calgary, AB T2E 4A5
                            <br/>
                            <a href="http://www.google.ca/local?hl=en&lr=&q=St+John+Lutheran&near=Calgary,+AB&latlng=51039877,-114080796,5519230273787071585" target="blank">Map It!</a>
                        </div>
                        <br/>
                        P: (403) 262-2862
                        <br/>
                        E: <a href="mailto:stjohnlc@telus.net">stjohnlc@telus.net</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="columnB">
            <div style="text-align:center;margin:15px;">
                <img src="/images/index/index/welcome_to_st_john.png"/>
            </div>
            <div id="slides">
                <div class="slides_container">
                    <div>
                        <img src="/images/index/index/slideshow/a.jpg">
                    </div>
                    <div>
                        <img src="/images/index/index/slideshow/b.jpg">
                    </div>
                </div>
            </div>
            <?echo $this->partial('index/_welcome.phtml');?>
            <section class="news">
                <img src="/images/index/index/news.png"/>
                <div>
                    <?echo $this->partial('index/_news.phtml');?>
                </div>
            </section>
        </div>
    </div>
</div>
