<div class="contentEditContainer">
    <select id="file">
        <option value="none" selected="selected" disabled="disabled">~~ Currently Live ~~</option>
     <?php foreach($this->menuItems as $content => $path) : ?>
        <option value="<?php echo htmlentities($path);?>"><?php echo htmlentities($content);?></option>
     <?php endforeach?>	
        <option value="none" disabled="disabled">~~ Backups ~~</option>
    <?php foreach($this->revertFiles as $content => $path) : ?>
        <option value=<?php echo htmlentities($path);?>><?php echo htmlentities($content);?></option>
    <?php endforeach?>
    </select>

    <input id="saveButton" type="button" value="Make Changes Live" disabled="disabled"/>
    <a class="help" href="http://www.w3schools.com/html/html_quick.asp" target="blank">(html help)</a>
    <iframe src="about:blank" id="preview-iframe"><p>Your browser does not support iframes.</p></iframe>
    <textarea id="editContent"></textarea>
</div>
