<div id="adminView">
  <div id="topDiv">
         <div class="select">
           <select id="veiwToUpdate" onchange="getFile()">
	         <option value="none" selected="selected">Select a File</option>
                  <?php foreach($this->menuItems as $key=>$value) : ?>
	                <option value=<?php echo $value;?>><?php echo $key;?></option>
                  <?php endforeach?>	
           </select>
         </div><!-- end select div -->


         <div id="saveButton">
            <input  type="button" value="Save" onclick="saveFile()" ></input>
         </div><!-- end saveButton div -->
         
         <div id="refreshButton">
            <input type="button" value="Refresh" onclick="refresh()"></input>
         </div><!-- end refreshButton div -->
       
         <div class='select'>
            <select id="revertFiles" onchange="getRevertFile()">
                <option value="none" selected="selected">Revert To Last Saved File</option>
                  <?php foreach($this->revertFiles as $value) : ?>
                    <option value=<?php echo $value;?>><?php echo $value;?></option>
                  <?php endforeach?>
            </select>
         </div><!-- end revertFiles div -->
        
         <div id="help">
             <a class="help" href="http://www.w3schools.com/html/html_quick.asp" onclick="newtab()"><img src="/images/admin/help1.jpg" height="25" width="25" />  HTML Help</a>
         </div>
  
  </div><!-- end topDiv -->

        <div id="previewContent">
            <iframe src="about:blank" id="preview-iframe" >
                   <p>Your browser does not support iframes.</p>
            </iframe>
        </div><!--end the preview div -->

        <div id="newContent">
            <form>
                <textarea id="editContent" onkeydown="display(1)" ></textarea>
            </form>
        </div><!-- end the admin text box div -->

</div><!-- end the adminView div -->
<script type="text/javascript" >
$(window).load(function() {
	checkCookie();
});
</script>

