<h1>
    <img src="/images/ministries/education/confirmation-and-educational-links/confirmation.png" alt="Confirmation And Educational Links"/>
</h1>  
Confirmation classes are held once a week from Sept/Oct to May/June Confirmation classes are for Grade 7 and 8 students. Please <a href="/about-us/contact-us">contact</a> the church for more details.<br/><br/>

<h1>
    <img src="/images/ministries/education/confirmation-and-educational-links/educational_links.png"/>
</h1>  
<section>
    <h2>University/college level</h2>
    <p>
    www.augustana.ca
    www.luthercollege.edu
    </p>
</section>
<section>
    <h2>Bible institutes</h2>
    <p>
    www.clbi.edu
    www.clbi.sk.ca
    </p>
</section>
<section>
    <h2>Seminary</h2> 
    <p>www.usask.ca/stu/luther</p>
</section>
