<div class="staticContent">
    <h1>Confirmation Classes</h1>
    Confirmation classes are held once a week from Sept/Oct to May/June Confirmation classes are for Grade 7 and 8 students. Please <a href="/about-us/contact-us">contact</a> the church for more details.<br/><br/>

    <h2>Educational Links</h2>
        <section>
            <h3>University/college level</h3>
            <p>
            www.augustana.ca
            www.luthercollege.edu
            </p>
        </section>
        <section>
            <h3>Bible institutes</h3>
            <p>
            www.clbi.edu
            www.clbi.sk.ca
            </p>
        </section>
        <section>
            <h3>Seminary</h3> 
            <p>www.usask.ca/stu/luther</p>
        </section>
</div>
