<section>
    <h1>
        <img src="/images/ministries/education/confirmation-and-educational-links/confirmation.png" alt="Confirmation And Educational Links" width="174px" height="53px"/>
    </h1>
    <p>
        Confirmation classes are held once a week from Sept/Oct to May/June Confirmation classes are for Grade 7 and 8 students. Please <a href="/about-us/contact-us">contact</a> the church for more details.
    </p>
</section>
<section style="margin-top:25px;">
    <h1>
        <img src="/images/ministries/education/confirmation-and-educational-links/educational_links.png" alt="Educational Links" width="247px" height="43px"/>
    </h1>  
    <h2>University/college level</h2>
    <a href="http://www.augustana.ca" target="blank">www.augustana.ca</a>
    <br/>
    <a href="http://www.luthercollege.edu" target="blank">www.luthercollege.edu</a>
    <h2 style="margin-top:15px">Bible Institutes</h2>
    <a href="http://www.clbi.edu" target="blank">www.clbi.edu</a>
    <br/>
    <a href="http://www.clbi.sk.ca" target="blank">www.clbi.sk.ca</a>
    <h2 style="margin-top:15px">Seminary</h2> 
    <a href="http://www.usask.ca/stu/luther">www.usask.ca/stu/luther</a>
</section>
