<h1 style="margin-bottom:12px">
    <img src="/images/ministries/education/huff-and-puff/huff_and_puff.png" alt="Huff And Puff"/>
</h1>
<div id="slides">
    <div class="slides_container">
        <div>
            <img src="/images/ministries/education/huff-and-puff/huffandpuff.jpg" alt="huff-and-puff train pic 1">
        </div>
        <div>
            <img src="/images/ministries/education/huff-and-puff/huffandpuff2.jpg" alt="huff-and-puff train pic 2">
        </div>
    </div>
</div>
<p style="margin-top:0">
    Created in the image of God, many people have an artistic flare.  The building of this model railroad is a way we can express our artistic or creative talents.  We welcome anyone who wishes to contribute their talents, or wishes to learn some modeling skills, to come and share in the fellowship and comeraderie as we create a miniature representation of the world around us, especially when it’s related to railroads.  The railroad club has been building on the layout, for the past six years and have made considerable headway.  We usually end our sessions by someone telling a railroad story, then close with prayer for the church and its people.  The original 4’ X 8’ section of the layout was donated by Trains & Such Hobby Shop. www.trains & such.com Most of the tracks, power packs, rolling stock, buildings and supplies have also been donated to us and we thank all the people who have been so kind to make these contributions.
</p>
<p>
    We meet Thursday afternoons from <b>2:00 - 4:00</b>.  If you would like to drop in and take a look at what’s been done or you would like to join the team please call pastor Arnie at <b>403-262-2862</b>.
</p>
