<div class="staticContent">
    <h1>Under 100 Club and Bible Study</h1>
    The Under 100 club is a group of women and men that meets once a month for fellowship, lunch and a bible study. The group is open to anyone 100 years old and younger, but if you are over 100 years old please come along as well!  
    <br/>
    The Under 100 Club is also responsible for organizing many excursions to interesting places in and around Calgary including museums, dinner theatres and concerts just to name a few. There is always room for more members either at the monthly meetings or on the excursions.
    <br/>
    <ul>
        <li>Head Smashed-in Buffalo Jump</li>
        <li>Rosebud Theater Dinner</li>
        <li>Drumheller Passion Play</li>
        <li>  Heritage Park Christmas Dinner</li>
    </ul>
</div>
