<h1>
    <img src="/images/ministries/education/under-100-club/under_100_club.png" alt="Under 100 Club"/>
</h1>
<p>
    The Under 100 club is a group of women and men that meets once a month for fellowship, lunch and a bible study. The group is open to anyone 100 years old and younger, but if you are over 100 years old please come along as well!  
</p>
<p>
    The Under 100 Club is also responsible for organizing many excursions to interesting places in and around Calgary including museums, dinner theatres and concerts just to name a few. There is always room for more members either at the monthly meetings or on the excursions. The following are places that we more commonly each year:
    <ul>
        <li>Head Smashed-in Buffalo Jump</li>
        <li>Rosebud Theater Dinner</li>
        <li>Drumheller Passion Play</li>
        <li>Heritage Park Christmas Dinner</li>
    </ul>
</p>
