<h1>Women’s Group and Bible Study</h1>
The St. John Lutheran Church Women’s group is an organization open to all women.
 Meetings are held on the second Tuesday of the month at noon and include a business meeting, Bible study and lunch. 
This organization is instrumental in planning and carrying out many important aspects of the life and mission at St. John. These include the Easter Sunday Breakfast, The Stampede Breakfast, the Fall Tea and Bazaar in November and the Thanksgiving Day Potluck supper. As well the ladies also serve meals at funerals and many other functions. 
When help is needed with mission projects such as the We Care kits for Canadian Lutheran World relief, the ladies group is always there to help.
