<h1>
    <img src="/images/ministries/education/womens-group/womens_group.png" alt="Woman Bible Study" width="219px" height="54px"/>
</h1>
<p>
    The Women’s group is open to all women and meet on the second Tuesday of every month at noon. A typical meeting includes discussing church events, a Bible study, and lunch.
</p>
<p>
    This group is instrumental in planning and carrying out many important aspects of the life and mission at St. John such as:
    <ul>
        <li>Easter Sunday Breakfast</li>
        <li>Stampede Breakfast</li>
        <li>Fall Tea and Bazaar</li>
        <li>Thanksgiving Day Potluck Supper</li>
        <li>Planning for involvment of wedding and funeral functions</li>
        <li>Helping with mission projects such as assembling <a href="/ministries_missions/clwr">We Care Kits</a> for Canadian Lutheran World Relief
    </ul>
</p>
<p style="text-align:center;padding-top:10px;">
    Please <a href="/about-us/contact-us">contact</a> the church for more details.
</p>
