<h1>
    <img src="/images/ministries/education/womens-group/womens_group.png" alt="Woman Bible Study"/>
</h1>
<p>
    The St. John Lutheran Church Women’s group is open to all women.
</p>
<p>
    Meetings are held on the second Tuesday of the month at noon and include a business meeting, Bible study and lunch.
</p>
<p>
    This group is instrumental in planning and carrying out many important aspects of the life and mission at St. John. These include the Easter Sunday Breakfast, The Stampede Breakfast, the Fall Tea and Bazaar in November and the Thanksgiving Day Potluck supper. As well the ladies also serve meals at funerals and many other functions.
</p>
<p>
    When help is needed with mission projects such as the We Care kits for Canadian Lutheran World relief, the ladies group is always there to help.
</p>
