<h1>
    <img src="/images/giving/index/secure_online_giving.png" alt="Secure Online Giving"/>
</h1>
<p>
    Your gift helps St. John Lutheran Church to continue its mission of ministering and spreading the word of our lord. Your charity will help support things like operating costs and our active role in the community. 
</p>
<section>
    <h2>Cheque \ Money Order</h2>
    <p>
        St. John Lutheran Church<br/> 
        204 6a Street NE <br/>
        Calgary, AB T2E 4A5<br/>
        Canada
    </p>
</section>
<section>
    <h2>Email \ Mobile</h2>
    <p>
        Email and mobile transfers can be sent to <b>admin@stjohncalgary.com</b>
    </p>
</section>
<section>
    <h2>Online</h2>
    <p>
        Perform a secure transaction using paypal. In the paypal form, ensure that you choose "gift", as there is no transaction fee associated to this method.
    </p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="GZB4LEV2LPT78">
        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
</section>
