<h1>
    <img src="/images/services/baptism/baptism.png" alt="Baptism" width="115px" height="54px"/>
</h1>
<p>
    We believe the Sacrament of Holy Baptism to be a free gift from God. As Lutheran Christians we baptise infants as well as adults. Through this Sacrament we believe that God liberates us from sin and death, makes us a child of God, and we become inheritors of eternal life.
</p>
<p>
    To be baptized simply requires belief that Jesus Christ is the only Son of God, sent by God to provide for humanity salvation and new life. In the case of young children, the parents and sponsors make a faith statement on behalf of the child. In later years the child at his/her Confirmation day, make their own profession of faith.
</p>
<p>
    In response to God’s gift of Baptism, we live our Christian life in service to God, and to our fellow human beings.
</p>
<h2>To arrange a baptism</h2>
<p>
    <ul> 
        <li>Please call our pastor at 403-262-2862 to make arrangements for the Baptism.</li>
        <li>Click <a href="/files/baptism.doc" >here</a> for the Baptismal Information Form. Fill in the information as best as you are able, and bring it with you when you meet with the pastor.</li>
    </ul>
    There is no charge for Baptism, but you are welcome to make a donation to St. John Lutheran Church if you so choose.
</p>
