<h1>
    <img src="/images/services/funeral/funeral.png" alt="Funeral"/>
</h1>  
Funerals or Memorial services at St. John Lutheran Church are conducted in a Christian atmosphere. We welcome members as well as those not associated with the church. 			
- Please contact the pastor at (403) 262-2862 to make the necessary arrangements
- Click here to download the information sheet and fill out as much as you are able. 			
- Bring the information sheet when you meet with the pastor to make arrangements.
Our women’s auxiliary are available to cater funeral receptions. Please contact Mrs. Dorothy Schumaker at (403) 262-2862 for more information. Funeral fees listed below. (Please arrange to have payments to the church prior to the actual funeral)<br/><br/>

<section>
    <h2>RENTAL RATES AND FEES</h2>
    <p>
    Organist (Alma Sloboda) - $150
    Custodian (Dorothy Schumaker) - $125
    Pastor - At Your Discretion ($300 suggested)
    Sanctuary - $40
    Sanctuary cheque payable to: St. John Lutheran Church
    Please note that the honorariums for the Organist, Custodian and Pastor are all to be paid individually, preferably by cash or cheque to each individual person.

    Thank you,
    St. John Lutheran Church Council
    </p>
</section>
