<h1>
    <img src="/images/services/funeral/funeral.png" alt="Funeral"/>
</h1>
<p>
    Funerals or Memorial services at St. John Lutheran Church are conducted in a Christian atmosphere. We welcome members as well as those not associated with the church.
</p>
<ul>
    <li>
        Please contact the pastor at (403) 262-2862 to make the necessary arrangements
    </li>
    <li>
        Click <a href="/files/funeral.doc" >here</a> to download the information sheet and fill out as much as you are able.
    </li>
    <li>
        Bring the information sheet when you meet with the pastor to make arrangements.
    </li>
</ul>
<p>
    Our women’s auxiliary are available to cater funeral receptions. Please contact Mrs. Dorothy Schumaker at (403) 262-2862 for more information. Funeral fees listed below. (Please arrange to have payments to the church prior to the actual funeral)
</p>
<h2>Rental Rates & Fees</h2>
<ul>
    <li>Organist (Alma Sloboda) - $150</li>
    <li>Custodian (Dorothy Schumaker) - $125</li>
    <li>Pastor - At Your Discretion ($300 suggested)</li>
    <li>Sanctuary - $40</li>
</ul>
<p>Sanctuary cheque payable to: St. John Lutheran Church</p>
<p>
    Please note that the honorariums for the Organist, Custodian and Pastor are all to be paid individually, preferably by cash or cheque to each individual person.
</p>
