<h1>
    <img src="/images/services/funeral/funeral.png" alt="Funeral" width="118px" height="42px"/>
</h1>
<div style="text-align:center">
    <?php echo $this->partial('layout/_picture.phtml', array('source' => '/images/services/funeral/service.jpg', 'alt' => 'Wedding'));?>
</div>
<p>
    Funerals or Memorial services at St. John Lutheran Church are conducted in a Christian atmosphere. We welcome members and non-members.
</p>
<ul>
    <li>
        Please contact the pastor at (403) 262-2862 to make the necessary arrangements
    </li>
    <li>
        Click <a href="/files/funeral.doc" >here</a> to download the information sheet and fill out as much as you are able.
    </li>
    <li>
        Bring the information sheet when you meet with the pastor to make arrangements.
    </li>
</ul>
<p>
    Our <a href="/ministries_education/womens-group">women’s group</a> is available to cater funeral receptions. Please contact Mrs. Dorothy Schumaker at (403) 262-2862 for more information. Funeral fees listed below. (Please arrange to have payments to the church prior to the actual funeral)
</p>
<h2>Rental Rates & Fees</h2>
<ul>
    <li>Organist (Alma Sloboda) - $150</li>
    <li>Custodian (Dorothy Schumaker) - $125</li>
    <li>Pastor - At Your Discretion ($300 suggested)</li>
    <li>Sanctuary - $40</li>
</ul>
<p>Sanctuary cheque payable to: St. John Lutheran Church</p>
<p>
    Please note that the honorariums for the Organist, Custodian and Pastor are all to be paid individually, preferably by cash or cheque to each individual person.
</p>
