<h1>
    <img src="/images/services/wedding/wedding.png" alt="Wedding"/>
</h1>  
Weddings at St. John Lutheran Church are welcome for members as well as those not associated with the 
church. All weddings conducted in our sanctuary are Christian weddings conducted by a minister and blessed by God.
We highly recommend all couples take a marriage preparation course prior to the wedding. Pre-marital classes are available through www.calgarycounselling.com. St. John members have the option of doing marriage preparation with their pastor.	
To Arrange For a Wedding at St. John:
- Please call our pastor at (403) 262-2862 to discuss your wedding plans.
- Click here to download the information sheet and fill in what you are able. Bring the information when 	booking the church or meeting with the pastor.
Please note, to reserve the church for your 	wedding requires a $200.00 deposit, which will be deducted from the rental fee. 	
See list of fees below.
(Please arrange all payments to be received by the church 2 weeks prior to the wedding)
RENTAL RATES AND FEES
Organist (Alma Sloboda) - $150 (includes rehearsal)
Custodian (Dorothy Schumaker) - $125
Pastor (Rev. Arnold Alksne)- At Your Discretion ($300 suggested)
Sanctuary - $400
Sanctuary cheque payable to: St. John Lutheran Church
Please note that the honorariums paid to the Organist, Custodian and Pastor are all to be paid individually, preferably by cash or cheque to each individual person.
A $200 deposit is required to book the church. Balance owed to be paid in full one month prior. If the balance is not received by the due date the church may be booked for other functions. 			
YOUR CO-OPERATION IS APPRECIATED.

Thank you,
St. John Lutheran Church Council
