<h1>
    <img src="/images/services/wedding/wedding.png" alt="Wedding"/>
</h1>  
<div style="text-align:center">
    <?php echo $this->partial('layout/_picture.phtml', array('source' => '/images/services/wedding/service.jpg', 'alt' => 'Wedding'));?>
    <div style="font-size:0.7em">Photo credit <a href="http://www.shuttersugar.com" target="blank">Shirrine Ocean</a></div>
</div>
<p>
    Weddings at St. John Lutheran Church are welcome to all. All weddings conducted in our sanctuary are Christian weddings conducted by a minister and blessed by God. We highly recommend all couples take a marriage preparation course prior to the wedding. Pre-marital classes are available through <a href="http://www.calgarycounselling.com" target="blank">www.calgarycounselling.com</a>. St. John members have the option of doing marriage preparation with their pastor.	
</p>
<h2>To Arrange For a Wedding at St. John</h2>
<ul>
    <li>
        Please call our pastor at (403) 262-2862 to discuss your wedding plans.
    </li>
    <li>
        Click <a href="/files/marriage_planning_form.pdf">here</a> to download the information sheet and fill in what you are able. Bring the information when booking the church or meeting with the pastor.
    </li>
</ul>
<h2>Rental Rates & Fees</h2>
<ul>
    <li>Organist (Alma Sloboda) - $150 (includes rehearsal)</li>
    <li>Custodian (Dorothy Schumaker) - $125</li>
    <li>Pastor (Rev. Arnold Alksne)- At Your Discretion ($300 suggested)</li>
    <li>Sanctuary - $400</li>
</ul>
<p>
    Sanctuary cheque payable to: St. John Lutheran Church
</p>
<p>
    Please note that the honorariums paid to the Organist, Custodian and Pastor are all to be paid individually, preferably by cash or cheque to each individual person.
</p>
<p>
    A $200 deposit is required to book the church, which will be deducted from the rental fee. Balance owed to be paid in full one month prior. If the balance is not received by the due date the church may be booked for other functions.
</p>
