<section>
    <h1>New</h1>
    <?php if (isset($this->error)) :?>
        <div class="error">
            <?php echo $this->error;?>
        </div>
    <?php endif;?>
    <form method="post" action="/admin/home_news/create"/>
        <label for="newsTitle">Title</label>
        <br/>
        <input type="text" id="newsTitle" name="newsTitle" value="<?php echo htmlentities($this->formValues['newsTitle']);?>" maxlength="100"/>
        <br/>
        <label for="newsBody">Body (<a href="http://www.bbcode.org/" target="blank">bbcode</a>) </label>
        <br/>
        <textarea id="newsBody" name="newsBody" rows="4" maxlength="20000"><?php echo htmlentities($this->formValues['newsBody']);?></textarea>
        <div id="newsBodyPreview" style="display:none"></div>
        <br/>
        <input type="submit" value="Add"/>
        <input type="button" id="previewButton" value="preview" onclick="Admin_Home_News.showPreview()" style="margin-left:10px"/>
        <input type="button" id="editButton" value="edit" onclick="Admin_Home_News.hidePreview()" style="display:none;margin-left:10px"/>
    </form>
</section>
<section class="newsAdmin">
    <?php if ($this->archived == 1) :?>
        <h1>Archived</h1>
        (<a href="/admin/home_news">view active</a>)
    <?php else: ?>
        <h1>Active</h1>
        (<a href="/admin/home_news?archived=1">view archived</a>)
    <?php endif;?>
    <section class="news">
    <?php
        foreach ($this->news as $item) :
            echo $this->partial(
                'home/_news.phtml',
                array(
                    'news' => $item,
                    'appendHTML' => '
                        <div style="text-align: right">
                            <a href="javascript:Admin_Home_News.deleteNews(' . $item->id . ',' . (int)$this->archived . ');">delete</a>
                        </div>
                    '
                )
            );
        endforeach;
    ?>
    </section>
</section>
