<section>
    <h1>New</h1>
<?php if (isset($this->uploadErrors)): ?>
    <div class="error">
        <?php foreach($this->uploadErrors as $error): ?>
                <?php echo htmlentities($error);?>
                <br/>
        <?php endforeach;?>
    </div>
<?php endif;?>
    <form enctype="multipart/form-data" action="/admin/file/upload" method="POST">
        <input name="file" id="file" type="file" onchange="this.form.submit();"/>
        <input type="button" onclick="$('#file').click();" value="Upload Image"/>
    </form>
</section>
<section>
    <h1>Current</h1>
<?php foreach($this->images as $value) : ?>
    <div>
        <a href="/images/dynamic/<?php echo htmlentities($value);?>" target="blank">/images/dynamic/<?php echo $value;?>
    </div>
<?php endforeach;?>
</section>
