<?php

$upload = new Zend_File_Transfer_Adapter_Http();
$upload->addValidator('Count', false, array('min' =>1, 'max' => 1))
       ->addValidator('IsImage', false, array('jpg', 'png', 'gif'))
       ->addValidator('Size', false, array('max' => '512kB'))
       ->setDestination(APPLICATION_PATH.'/../public/images/admin/');
       
if (!$upload->isValid())
{
    throw new Exception('Bad image data: '.implode(',', $upload->getMessages()));
}

try {
        $upload->receive();
        echo "<b>File received succesfully, you will be redirected to the image page shortly.  If not click
        <a href='http://localhost/admin/file'>here.</a></b>
              <script type='text/javascript'>
                setTimeout(function(){
                 window.location = 'http://localhost/admin/file';},
                3000);
              </script>";
} 
catch (Zend_File_Transfer_Exception $e) 
{
        throw new Exception('Bad image data: '.$e->getMessage());
}

?>
