With its beautiful stained glass windows, carved woodwork and soaring cathedral ceiling St. John Lutheran Church is an inspirational place of worship and prayer. The Fellowship Hall in our basement along with its full kitchen is wheelchair accessible and available for large gatherings.You can easily access the church from Memorial Drive and Edmonton Trail. We have on-street parking during the week as well as use of a school parking lot across the street on weekends.
<br/><br/>
Welcome to our website, we look forward to meeting you!
<br/><br/>
