<p>
    We welcome everyone to come, worship, and learn about our Christian faith. Our traditional services teach the Word of the Lord and how His teachings apply today. With its beautiful stained glass windows, carved woodwork and soaring cathedral ceiling, St. John Lutheran Church is an inspirational place of worship and prayer.
</p>
<p>
    St. John also offers a large Fellowship Hall complete with a full kitchen that is wheelchair accessible and available for large gatherings. The congregation occasionally uses the hall for events such as after service potlucks, bazaars, and celebrating member birthdays.
</p>
<p>
    Our church is located in the heart of Bridgeland with use of on street parking during the week and a school parking lot during the weekends.
</p>
<p>
    We look foward to seeing you at our next service!
</p>
