<h1>Acadia Place</h1>
As Christians, we are called to help our brothers and sisters. Acadia Place is an ecumenical project with other local agencies to end family homelessness in Calgary. By paying down the 1.5 million dollar mortgage at Acadia Place, previously homeless families can have rents that they can afford and break the cycle of homelessness. St. John has a history of helping the homeless. We were one of the first churches to act as hosts for Inn from the Cold, where we often hosted homeless families. This is the next step in our work to help homeless families find permanent housing.
Members of St. John along with members of many other Calgary area churches have ongoing opportunities to donate money as well as time to help residents living at Acadia Place.

For more information on the Acadia Place project please visit www.acadiaplace.com
