<h1>
    <img src="/images/ministries/missions/acadia-place/acadia_place.png" alt="Acadia Place" width="189px" height="44px"/>
</h1>
<p>
    As Christians, we are called to help our brothers and sisters. Acadia Place is an ecumenical project with other local agencies to end family homelessness in Calgary. By paying down a 1.5 million dollar mortgage at Acadia Place, previously homeless families can have rents that they can afford and break the cycle of homelessness. Members of St. John, along with other Calgary area churches, have ongoing opportunities to donate money and time to help residents living at Acadia Place.
</p>
<p>
    For more information on the Acadia Place project please visit <a href="http://www.acadiaplace.com" target="blank">www.acadiaplace.com</a>.
</p>
