<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Admin Page</title>
	<link href="css/admin.css" media="screen" rel="stylesheet" type="text/css"/> 
   	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/admin/index.js"></script>
    </head>
    <body>
        <div class="layout">
            <div class="content">
                <?php echo $this->layout()->content;?>
            </div>
        </div>
    </body>
</html>
