<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title></title>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
    </head>
    <body>
        <div class="layout">
            <header>
                <img src="/images/layout/logo.png"/>
                <?php echo $this->navigation()->menu();?>
            </header>
            <div class="content">
                <?php echo $this->layout()->content;?>
            </div>
            <div class="layoutBackground"></div>
        </div>
    </body>
</html>
