<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title></title>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
        <script type="text/javascript">
            $(document).ready(
                function () {
                    var offset = $('.content').height() + 40;
                    $('.layoutBackground')
                        .height(offset)
                        .css('top', '-' + offset + 'px');
                }
            );
        </script>
    </head>
    <body>
        <div class="layout">
            <header>
                <img src="images/layout/logo.png"/>
                <nav>
                    <?php echo $this->navigation()->menu();?>
                </nav>
            </header>
            <div class="content">
                <?php echo $this->layout()->content;?>
            </div>
            <div class="layoutBackground"></div>
        </div>
    </body>
</html>
