<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title></title>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
        <script type="text/javascript">
            function resizeLayout()
            {
                var offset = $('.content').height() + 145;
                $('.layoutBackground')
                    .height(offset)
                    .css('top', '-' + offset + 'px');
            }
            $(document).ready(resizeLayout);
            $(window).resize(resizeLayout);
        </script>
    </head>
    <body>
        <div id="popupMask" style="display:none;"></div>
        <div id="popupContainer" style="display:none;"><div id="popupContent"></div></div>
        <div class="layout">
            <header>
                <img src="/images/layout/logo.png"/>
                <nav>
                    <?php echo $this->navigation()->menu();?>
                </nav>
            </header>
            <div class="content">
                <?php echo $this->layout()->content;?>
            </div>
            <div class="layoutBackground"></div>
        </div>
    </body>
</html>
