<div id="adminView">
  <div id="topDiv">
      <form action="/home/christopher/branches/st_john/application/modules/Admin/views/scripts/image.php">
          <select id="veiwToUpdate" onchange="getFile()">
	        <option value="none" selected="selected">Select a File</option>
                  <?php foreach($this->menuItems as $key=>$value) : ?>
	                <option value=<?php echo $key;?>><?php echo $value;?></option>
                  <?php endforeach?>	
         </select>
      </form>
     <div id="imageButton">
        <input type="button" value="Upload Image" onclick="uploadImage()"></input>
     </div><!-- end imageButton div -->
     <div id="saveButton">
        <input  type="button" value="Save" onclick="saveFile()" ></input>
    </div><!-- end saveButton div -->
     <div id="help">
         <a class="help" href="http://www.w3schools.com/html/html_quick.asp" onclick="newtab()"><img src="/images/admin/help1.jpg" height="25" width="25" />  HTML Help</a>
     </div>
  
  </div><!-- end topDiv -->

  <div id="previewContent">
    <iframe src="about:blank" id="preview-iframe" >
           <p>Your browser does not support iframes.</p>
    </iframe>
  </div><!--end the preview div -->
  <div id="newContent">
	<form>
		<textarea id="editContent" onkeydown="display()" ></textarea>
	</form>
  </div><!-- end the admin text box div -->
  

</div><!-- end the adminView div -->
