<?php $controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>
<nav>
    <h1>Admin Menu</h1>
    <h2>Internal</h2>
    <ul>
        <li onclick="window.location = '/admin/index'"
            class="<?php if (strtolower($controllerName)== 'index') : echo 'navSelect'; endif;?>" >
            Main
        </li>
        <li onclick="window.location = '/admin/home_event'"
            class="<?php if (strtolower($controllerName)== 'home_event') : echo 'navSelect'; endif;?>" >
            Home - Events
        </li>
        <li onclick="window.location = '/admin/home_news'"
            class="<?php if (strtolower($controllerName)== 'home_news') : echo 'navSelect'; endif;?>" >
            Home - News
        </li>
        <li onclick="window.location = '/admin/content'"
            class="<?php if (strtolower($controllerName)== 'content') : echo 'navSelect'; endif;?>" >
            Content
        </li>
        <li onclick="window.location = '/admin/file'"
            class="<?php if (strtolower($controllerName)== 'file') : echo 'navSelect'; endif;?>" >
            Upload Files
        </li>
        <li onclick="window.location = '/admin/user/manage'"
            class="<?php if (strtolower($controllerName)== 'user') : echo 'navSelect'; endif;?>" >
            Accounts
        </li>
    </ul>
    <h2>External</h2>
    <ul>
        <li onclick="window.open('https://login.mailchimp.com/')">
            Registered Email
        </li>
        <li onclick="window.open('https://signin.ebay.com/ws/eBayISAPI.dll?SellItem')">
            Ebay - Donations
        </li>
        <li onclick="window.open('https://my.justhost.com/cgi-bin/cplogin')">
            Web Host
        </li>
    </ul>
    <a href="/admin/user/logout" class="logout">Log Out</a>
</nav>
