<?php $controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>
<nav>
    <h1>Admin Menu</h1>
    <ul>
        <li onclick="window.location = '/admin/index'"
            class="<?php if (strtolower($controllerName)== 'index') : echo 'navSelect'; endif;?>" >
            Admin Main
        </li>
        <li onclick="window.location = '/admin/home_event'"
            class="<?php if (strtolower($controllerName)== 'home_event') : echo 'navSelect'; endif;?>" >
            Home - Events
        </li>
        <li onclick="window.location = '/admin/home_news'"
            class="<?php if (strtolower($controllerName)== 'home_news') : echo 'navSelect'; endif;?>" >
            Home - News
        </li>
        <li onclick="window.location = '/admin/content'"
            class="<?php if (strtolower($controllerName)== 'content') : echo 'navSelect'; endif;?>" >
            Content
        </li>
        <li onclick="window.location = '/admin/file'"
            class="<?php if (strtolower($controllerName)== 'content') : echo 'navSelect'; endif;?>" >
            Upload Files
        </li>
        <li onclick="window.location = '/admin/misc/registeredemail'"
            class="<?php if (strtolower($controllerName)== 'registeredemail') : echo 'navSelect'; endif;?>" >
            Registered Email
        </li>
        <li onclick="window.location = '/admin/misc/email'"
            class="<?php if (strtolower($controllerName)== 'email') : echo 'navSelect'; endif;?>" >
            Admin Accounts
        </li>
    </ul>
    <a href="/admin/index/logout" class="logout">Log Out</a>
</nav>
