<?php
//saves the contents of the admin text area to a file

   $html = $this->params['html'];
   $fileToUpdate = $this->params['file'];
   
   //strip forward slashes from the file path to ensure unique revert file names
   $revertFile = str_replace('/','',$fileToUpdate);
   
   
   $newFile = APPLICATION_PATH.'/modules/Admin/views/scripts/content/index/revertfiles/'.$revertFile;
   $oldFile = APPLICATION_PATH.'/views/scripts/'.$fileToUpdate;
   
   //get the contents of the old file so it can be save to a revert file
   $contents = file_get_contents($oldFile);
   
   $writeToRevertFile = fopen($newFile, "w+");
   fwrite($writeToRevertFile, $contents);
   fclose($writeToRevertFile);
   
   //after the revert file is saved replace the contents of the old file
    
   $SaveFile = fopen($oldFile, "w+");
   fwrite($SaveFile, $html);
   fclose($SaveFile);
   
?>
